[package]
authors = ["Peter Allin <peter@peca.dk>"]
edition = "2018"
license = "MIT"
name = "mgs"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
git2 = "0.13"
itertools = "0.9"
structopt = "0.3"
walkdir = "2.3"
