name: Release

on:
  push:
    tags:
      - "rel-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
      - name: build
        run: cargo build --release
      - name: Copy to output
        run: |
          mkdir -p output/mgs-${{ steps.vars.outputs.version }}
          cp target/release/mgs output/mgs-${{ steps.vars.outputs.version }}
          cp LICENSE output/mgs-${{ steps.vars.outputs.version }}
          tar zcf output/mgs-linux-${{ steps.vars.outputs.version }}.tar.gz -C output mgs-${{ steps.vars.outputs.version }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: output/mgs-linux-${{ steps.vars.outputs.version }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs:
      - linux
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.linux.outputs.version }}
          release_name: ${{ needs.linux.outputs.version }}
          draft: false
          prerelease: false
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux
      - name: Debug
        run: ls -R
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mgs-linux-${{ needs.linux.outputs.version }}.tar.gz
          asset_name: mgs-linux-${{ needs.linux.outputs.version }}.tar.gz
          asset_content_type: application/gzip
